# Generated by Django 3.2.13 on 2024-05-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='les_produits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages\\static\\pages\\img'),
        ),
    ]
