# Generated by Django 3.2.13 on 2024-05-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages\\static\\pages\\img'),
        ),
    ]
