# Generated by Django 3.2.13 on 2024-05-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_achat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
