# Generated by Django 3.2.13 on 2024-05-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_achat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
